!--
  Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
  Command: npx @threlte/gltf@2.0.3 --root /models/ --types --printwidth 120 --precision 2
  Author: Moshe Caine (https://sketchfab.com/mosheca)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/tulips-lidar-scan-018e6b7e03b34303a7465448674399b8
  Title: Tulips LIDAR scan
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group, Material } from 'three';
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { createTransition, useGltf, useSuspense } from '@threlte/extras';
  import { cubicOut } from 'svelte/easing';

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
        Object_2: THREE.BufferGeometry
        Object_3: THREE.BufferGeometry
        Object_4: THREE.BufferGeometry
        Object_5: THREE.BufferGeometry
        Object_6: THREE.BufferGeometry
        Object_7: THREE.BufferGeometry
        Object_8: THREE.BufferGeometry
        Object_9: THREE.BufferGeometry
        Object_10: THREE.BufferGeometry
        Object_11: THREE.BufferGeometry
    }
    materials: {
      ['Scene_-_Root']: THREE.PointsMaterial
    }
  }

  const suspend = useSuspense()
  const gltf = suspend(useGltf<GLTFResult>('models/tulips.glb', { useDraco: true }))

  const component = forwardEventHandlers()

  const pointSize = 500

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group  rotation={[-Math.PI / 2, 0, 0]} position={[-10, 250, -80]} scale={0.5}>
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_2.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_3.geometry} material={gltf.materials['Scene_-_Root']} />;
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_5.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_7.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_8.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_9.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_10.geometry} material={gltf.materials['Scene_-_Root']} />
      <T.Points scale={pointSize} geometry={gltf.nodes.Object_11.geometry} material={gltf.materials['Scene_-_Root']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
